
package view;

import model.F01_Bill_details;
import model.F02_Item_details;
import model.F03_BillTableModel;
import model.F04_ItemTableModel;
import controller.A01_control;
import controller.A02_loadFile;
import controller.A03_Select;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Lenovo
 */
public class JF01_bill_of_sales_screen_form extends javax.swing.JFrame {

    public JF01_bill_of_sales_screen_form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        bill_table = new javax.swing.JTable();
        bill_table.getSelectionModel().addListSelectionListener(sellectController);
        create_bill_button = new javax.swing.JButton();
        create_bill_button.addActionListener(controller);
        delete_bill_button = new javax.swing.JButton();
        delete_bill_button.addActionListener(controller);
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        items_table = new javax.swing.JTable();
        add_item_button = new javax.swing.JButton();
        add_item_button.addActionListener(controller);
        remove_item_button = new javax.swing.JButton();
        remove_item_button.addActionListener(controller);
        jLabel5 = new javax.swing.JLabel();
        bill_number_filed = new javax.swing.JTextField();
        customer_name_filed = new javax.swing.JTextField();
        bill_date_filed = new javax.swing.JTextField();
        bill_total_filed = new javax.swing.JTextField();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        load_file_menu_item = new javax.swing.JMenuItem();
        load_file_menu_item.addActionListener(controller);
        save_file_menu_item = new javax.swing.JMenuItem();
        save_file_menu_item.addActionListener(controller);
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        Exit_programming = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 255));

        bill_table.setBorder(new javax.swing.border.MatteBorder(null));
        bill_table.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bill_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        bill_table.setGridColor(new java.awt.Color(0, 102, 102));
        jScrollPane1.setViewportView(bill_table);

        create_bill_button.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        create_bill_button.setForeground(new java.awt.Color(51, 51, 255));
        create_bill_button.setText("Create New Bill");
        create_bill_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                create_bill_buttonActionPerformed(evt);
            }
        });

        delete_bill_button.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        delete_bill_button.setForeground(new java.awt.Color(204, 0, 0));
        delete_bill_button.setText("Delete Bill");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 255));
        jLabel1.setText("Bill Number:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 255));
        jLabel2.setText("Bill Date:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 255));
        jLabel3.setText("Customer Name:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 255));
        jLabel4.setText("Bill Total:");

        items_table.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        items_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(items_table);

        add_item_button.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        add_item_button.setText("Add new Item");

        remove_item_button.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        remove_item_button.setForeground(new java.awt.Color(204, 0, 0));
        remove_item_button.setText("Remove Item");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 153));
        jLabel5.setText("Invoice System");

        bill_number_filed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bill_number_filedActionPerformed(evt);
            }
        });

        customer_name_filed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customer_name_filedActionPerformed(evt);
            }
        });

        bill_total_filed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bill_total_filedActionPerformed(evt);
            }
        });

        jMenu3.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jMenu3.setText("File");

        load_file_menu_item.setText("Load File");
        load_file_menu_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                load_file_menu_itemActionPerformed(evt);
            }
        });
        jMenu3.add(load_file_menu_item);

        save_file_menu_item.setText("Save File");
        jMenu3.add(save_file_menu_item);
        jMenu3.add(jSeparator1);

        Exit_programming.setText("Exit");
        Exit_programming.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Exit_programmingActionPerformed(evt);
            }
        });
        jMenu3.add(Exit_programming);

        jMenuBar2.add(jMenu3);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(create_bill_button)
                .addGap(80, 80, 80)
                .addComponent(delete_bill_button, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(add_item_button, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(remove_item_button, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(38, 38, 38)
                            .addComponent(bill_total_filed))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(38, 38, 38)
                            .addComponent(bill_number_filed, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(customer_name_filed, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(38, 38, 38)
                            .addComponent(bill_date_filed)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(310, 310, 310))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bill_number_filed, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bill_date_filed, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(customer_name_filed, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bill_total_filed)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(delete_bill_button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(create_bill_button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add_item_button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(remove_item_button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void create_bill_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_create_bill_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_create_bill_buttonActionPerformed

    private void load_file_menu_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_load_file_menu_itemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_load_file_menu_itemActionPerformed

    private void bill_number_filedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bill_number_filedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bill_number_filedActionPerformed

    private void customer_name_filedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customer_name_filedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customer_name_filedActionPerformed

    private void bill_total_filedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bill_total_filedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bill_total_filedActionPerformed

    private void Exit_programmingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Exit_programmingActionPerformed
        // TODO add your handling code here:
        JFrame  f = new JFrame("Exit");
      if(JOptionPane.showConfirmDialog(f,"confirm if you want to exit","Exit" ,JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION)
      {
     
          System.exit(0);
      }
    }//GEN-LAST:event_Exit_programmingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new JF01_bill_of_sales_screen_form().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Exit_programming;
    private javax.swing.JButton add_item_button;
    private javax.swing.JTextField bill_date_filed;
    private javax.swing.JTextField bill_number_filed;
    private javax.swing.JTable bill_table;
    private javax.swing.JTextField bill_total_filed;
    private javax.swing.JButton create_bill_button;
    private javax.swing.JTextField customer_name_filed;
    private javax.swing.JButton delete_bill_button;
    private javax.swing.JTable items_table;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem load_file_menu_item;
    private javax.swing.JButton remove_item_button;
    private javax.swing.JMenuItem save_file_menu_item;
    // End of variables declaration//GEN-END:variables


    private ArrayList<F01_Bill_details> bills;

     private A01_control controller = new A01_control(this);
     private A03_Select sellectController = new A03_Select(this);
     
     
    //create table 
    private F03_BillTableModel invoiceTableModel;

    public ArrayList<F01_Bill_details> getBills() {
        if(bills == null)
            bills = new ArrayList<>();
  
        return bills;
    }
  
    
    
  

    public void setBills(ArrayList<F01_Bill_details> bills) {
        this.bills = bills;
    }

    // get data for table invoice
    public F03_BillTableModel getInvoiceTableModel() {
        if(invoiceTableModel ==null)
        {
            invoiceTableModel = new F03_BillTableModel(getBills());
        }
        return invoiceTableModel;
    }
    //set data in table frame (invoice)
    public void setInvoiceTableModel(F03_BillTableModel invoiceTableModel) {
        this.invoiceTableModel = invoiceTableModel;
    }

   
    
    
    
    
       //get name of customer
    public JTextField getCustomer_name_label() {
        return customer_name_filed;
    }
 

    // get date in label of date
    public JTextField getBill_date_label() {
        return bill_date_filed;
    }
   
    // number of bill
    public JTextField getBill_number_label() {
        return bill_number_filed;
    }
  
    
    public JTable getBill_table() {
        return bill_table;
    }

    // get total of bill
    public JTextField getBill_total_label() {
        return bill_total_filed;
    }

 
    //get table of items to insert data
    public JTable getItems_table() {
        return items_table;
    }
  
    //getaction from controller class
    public A01_control getController() {
        return controller;
    }
    //method to retrn Id of new bill created
    public int getNextBillNum(){
        int num =0;
        for(F01_Bill_details bill :getBills()){
            if(bill.getId()>num)
                num = bill.getId();
    }
        return ++num;
    }
}

